### ISSUE TITLE
Suggestion: make stremio-local-addon opt-out

### ISSUE THREAD

**Issue by MuTLY** [Stremio/stremio-local-addon#20]
Currently there is no way to disable or uninstall this addon.

Please make it opt-out, giving the user a choice. As an example, I have several videos on my local storage that I don't want to be visible on Stremio. It could be porn, it could be private business videos, it could be family related videos, anything.

~~I did a test and Stremio even scans **hidden (+h) folders** on the drive for media. This is no good.~~

Apologies: in reality, it scanned a folder with several `.torrent` files on it. This folder is sitting inside my "Documents" folder, and that's what was showing on the "local media" section of Stremio.

**Comment by Ivshti** [comment]
Keep in mind that this scan, while it looks scary since it appears in the logs, does not mean the file will be shown in Stremio.

There are many conditions that are just based on RegEx parsing, and if they do not succeed, the file won't ever appear in Stremio. For example, the file has to contain a year or a season/episode stamp, and has to be over a certain size. Finally, the name has to be matched in an internal table of IMDB names.

That said, you have a fair point. We should make an option to disable scanning. Disabling the whole addon is not the best idea cause it's responsible for opening BitTorrent files and a few other things.
